# Generated by Django 5.0.1 on 2024-02-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kenindia_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kenindia_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_name', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Printer_name', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toner_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_name', models.CharField(max_length=500)),
                ('Staff_ID', models.CharField(default='', max_length=500, unique=True)),
                ('Department', models.CharField(default='', max_length=500)),
                ('Location', models.CharField(default='', max_length=500)),
                ('Toner_name', models.CharField(default='', max_length=500)),
                ('printer_name', models.CharField(default='', max_length=500)),
                ('issued', models.BooleanField(default=False)),
                ('Date_of_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toner', models.CharField(default='', max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('printer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.printer')),
            ],
        ),
    ]
