# Generated by Django 5.0.1 on 2024-02-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0002_toner_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
