# Generated by Django 5.0.1 on 2024-02-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0003_alter_toner_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toner',
            old_name='Toner',
            new_name='Toner_name',
        ),
    ]
