# Generated by Django 5.0.1 on 2024-02-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0004_rename_toner_toner_toner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toner_request',
            name='Toner_name',
        ),
        migrations.AddField(
            model_name='toner_request',
            name='toner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toner.toner'),
        ),
    ]
