# Generated by Django 5.0.1 on 2024-02-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0005_remove_toner_request_toner_name_toner_request_toner'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner_request',
            name='_previous_issued',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
