# Generated by Django 5.0.1 on 2024-02-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toner', '0008_delete_kenindia_department_delete_kenindia_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toner_request',
            name='printer_name',
        ),
        migrations.RemoveField(
            model_name='toner',
            name='printer_name',
        ),
        migrations.RemoveField(
            model_name='toner_request',
            name='toner',
        ),
        migrations.RemoveField(
            model_name='toner_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='Toner',
        ),
        migrations.DeleteModel(
            name='Toner_Request',
        ),
    ]
