# Generated by Django 5.0.1 on 2024-02-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_kenindia_department_kenindia_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Printer_name', models.CharField(max_length=500)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Toner_name', models.CharField(default='', max_length=500)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('printer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.printer')),
            ],
        ),
        migrations.CreateModel(
            name='Toner_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_staffid', models.CharField(blank=True, max_length=50, null=True)),
                ('user_staffname', models.CharField(blank=True, max_length=255, null=True)),
                ('user_department', models.CharField(blank=True, max_length=255, null=True)),
                ('user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('issued', models.BooleanField(default=False)),
                ('Date_of_request', models.DateTimeField(auto_now_add=True)),
                ('printer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.printer')),
                ('toner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.toner')),
            ],
        ),
    ]
