# Generated by Django 5.0.1 on 2024-05-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0007_printer_toner_toner_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toner',
            name='printer_name',
        ),
    ]
